// // File generated by FlutterFire CLI.
// // ignore_for_file: type=lint
// import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
// import 'package:flutter/foundation.dart'
//     show defaultTargetPlatform, TargetPlatform;

// /// Default [FirebaseOptions] for use with your Firebase apps.
// ///
// /// Example:
// /// ```dart
// /// import 'firebase_options.dart';
// /// // ...
// /// await Firebase.initializeApp(
// ///   options: DefaultFirebaseOptions.currentPlatform,
// /// );
// /// ```
// class DefaultFirebaseOptions {
//   static FirebaseOptions get currentPlatform {
//     switch (defaultTargetPlatform) {
//       case TargetPlatform.android:
//         return android;
//       case TargetPlatform.iOS:
//         return ios;
//       // case TargetPlatform.macOS:
//       //   return macos;
//       // case TargetPlatform.windows:
//       //   return windows;
//       case TargetPlatform.linux:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for linux - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       default:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions are not supported for this platform.',
//         );
//     }
//   }

//   static const FirebaseOptions android = FirebaseOptions(
//     apiKey: 'AIzaSyBZFLI-7bJZ5c5BHHxWqWEqJ0-BJVoQIJw',
//     appId: '1:889128706432:android:8ece41be466ee4bda92165',
//     messagingSenderId: '889128706432',
//     projectId: 'puchoai-3206a',
//     storageBucket: 'puchoai-3206a.firebasestorage.app',
//   );

//   static const FirebaseOptions ios = FirebaseOptions(
//     apiKey: 'AIzaSyCLEvHYBQGU9J3H0dkOGg1BAf-hE7vquGM',
//     appId: '1:889128706432:ios:06725951d57c16c0a92165',
//     messagingSenderId: '889128706432',
//     projectId: 'puchoai-3206a',
//     storageBucket: 'puchoai-3206a.firebasestorage.app',
//     iosBundleId: 'com.puchoai.app',
//   );
// }
